coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 0%

comment:
  layout: 'header, diff, flags, files'
  behavior: default
  require_changes: false
